name: 'Preview'
description: 'PR previews for your mobile app'
# Define your inputs here.
inputs:
  app-path:
    description: "path to the build .apk or .aab file"
    required: true

  pkg-name:
    description: "the app's package id ie com.example.app"
    required: true

  api-key:
    description: "your workspace api key found in your workspace settings"
    required: true
runs:
  using: composite
  steps:
    - uses: actions/github-script@v7
      id: get_pr_data
      with:
        script: |
          return (
            await github.rest.repos.listPullRequestsAssociatedWithCommit({
              commit_sha: context.sha,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
          ).data[0];
    - name: "Quill upload"
      id: quill_upload
      shell: bash
      run: |
        gitHost=github
        owner=${{ github.repository_owner }}
        repoName=${{ github.event.repository.name }}
        prId=${{ fromJson(steps.get_pr_data.outputs.result).number}}
        author=${{ fromJson(steps.get_pr_data.outputs.result).user.login }}
        title=${{ fromJson(steps.get_pr_data.outputs.result).title }}

        echo $gitHost
        echo $owner
        echo $repoName
        echo $prId

        resp=$(curl -F "apk=@${{ inputs.app-path }}" "https://api.getquill.dev/preview?api_key=${{ inputs.api-key }}" -F gitHost=$gitHost -F owner=$owner -F repoName=$repoName -F prId=$prId -F author=$author -F title=$title -F pkg=${{ inputs.pkg-name }})

        echo $resp
        echo "resp=$resp" >> $GITHUB_OUTPUT
    - uses: mshick/add-pr-comment@v2
      with:
        message: |
          [QA Review On Quill](${{ fromJson(steps.quill_upload.outputs.resp).previewUrl }})
