name: 'Preview'
description: 'PR previews for your mobile app'
# Define your inputs here.
inputs:
  app-path:
    description: "path to the build .apk or .aab file"
    required: true

  pkg-name:
    description: "the app's package id ie com.example.app"
    required: true

  api-key:
    description: "your workspace api key found in your workspace settings"
    required: true
runs:
  using: composite
  steps:
    - uses: actions/github-script@v7
      id: get_pr_data
      with:
        script: |
          const prData = (
            await github.rest.repos.listPullRequestsAssociatedWithCommit({
              commit_sha: context.sha,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
          );
          
          console.log("Pull Request Data: ", prData); // This will print prData to the action logs
          
          return prData;
    - name: "Quill upload"
      id: quill_upload
      shell: bash
      run: |
        gitHost=github
        owner=${{ github.repository_owner }}
        repoName=${{ github.event.repository.name }}
        prData=$(fromJson(steps.get_pr_data.outputs.result))
        echo "PR Data: ${{github.event.pull_request.number}}"
        if [ -z "$prData" ]; then
          echo "Error: Could not retrieve pull request data."
          exit 1
        fi
        # prId=${{ fromJson(steps.get_pr_data.outputs.result).number}}
        # author=${{ fromJson(steps.get_pr_data.outputs.result).user.login }}
        # title=${{ fromJson(steps.get_pr_data.outputs.result).title }}
        prId=${{github.event.pull_request.number}}
        author=${{ github.event.pull_request.user.login }}
        title=${{ github.event.pull_request.title }}

        echo $title
        echo $prId
        echo $author

        resp=$(curl -F "apk=@${{ inputs.app-path }}" "https://api.getquill.dev/preview?api_key=${{ inputs.api-key }}" -F gitHost=$gitHost -F owner=$owner -F repoName=$repoName -F prId=$prId -F author=$author -F title=$title -F pkg=${{ inputs.pkg-name }})

        echo "resp=$resp" >> $GITHUB_OUTPUT
    - uses: mshick/add-pr-comment@v2
      with:
        message: |
          [QA Review On Quill](${{ fromJson(steps.quill_upload.outputs.resp).previewUrl }})
