name: 'Preview'
description: 'PR previews for your mobile app'
# Define your inputs here.
inputs:
  app-path:
    description: "path to the build .apk or .aab file"
    required: true

  pkg-name:
    description: "the app's package id ie com.example.app"
    required: true

  api-key:
    description: "your workspace api key found in your workspace settings"
    required: true
runs:
  using: composite
  steps:
    - name: "Quill upload"
      id: quill_upload
      shell: bash
      run: |
        gitHost=github
        owner=${{ github.repository_owner }}
        repoName=${{ github.event.repository.name }}
        prData=${{github.event.pull_request}}
        
        if [ -z "$prData" ]; then
          echo "Error: Could not retrieve pull request data."
          exit 1
        fi
        
        prId=${{prData.number}}
        author=${{prData.user.login}}
        title=${{prData.title}} 

        echo $title
        echo $prId
        echo $author

        resp=$(curl -F "apk=@${{ inputs.app-path }}" "https://api.getquill.dev/preview?api_key=${{ inputs.api-key }}" -F gitHost=$gitHost -F owner=$owner -F repoName=$repoName -F prId=$prId -F author=$author -F title=$title -F pkg=${{ inputs.pkg-name }})

        echo "resp=$resp" >> $GITHUB_OUTPUT
    - uses: mshick/add-pr-comment@v2
      with:
        message: |
          [QA Review On Quill](${{ fromJson(steps.quill_upload.outputs.resp).previewUrl }})
